import type { AuditCategories } from '@/lib/audit/types';

const CATEGORY_LABELS: Record<string, string> = {
  seo: 'SEO', trust: 'Trust & Credibility', ux: 'UX Signals',
  performance: 'Performance', mobile: 'Mobile', accessibility: 'Accessibility',
};

const STATUS_ICON: Record<string, string> = {
  pass: '✅', warning: '⚠️', fail: '❌',
};

// ── Markdown export ───────────────────────────────────────────────────────────

export function generateMarkdown(
  url: string,
  overallScore: number,
  categories: Partial<AuditCategories>,
  scannedAt?: string,
): string {
  const date = scannedAt
    ? new Date(scannedAt).toLocaleString('en-GB', { dateStyle: 'long', timeStyle: 'short' })
    : new Date().toLocaleString('en-GB', { dateStyle: 'long', timeStyle: 'short' });

  const scoreLabel =
    overallScore >= 80 ? 'Good' : overallScore >= 60 ? 'Needs work' : 'Poor';

  const lines: string[] = [
    `# Website UX Audit: ${url}`,
    ``,
    `**Overall Score: ${overallScore}/100** (${scoreLabel})`,
    `*Scanned: ${date}*`,
    `*Powered by Webbeet - https://ux-audit.exlinelabs.co.uk*`,
    ``,
    `---`,
    ``,
  ];

  const ORDER = ['seo', 'trust', 'ux', 'performance', 'mobile', 'accessibility'];

  for (const key of ORDER) {
    const cat = (categories as Record<string, import('@/lib/audit/types').CategoryResult | undefined>)[key];
    if (!cat) continue;

    const label = CATEGORY_LABELS[key] ?? key;

    if (cat.unavailable) {
      lines.push(`## ${label} — Unavailable`);
      lines.push(`*This category could not be checked (timed out or blocked).*`);
      lines.push('');
      continue;
    }

    lines.push(`## ${label} — ${cat.score}/100`);
    lines.push('');
    lines.push('| Check | Status | Value | Notes |');
    lines.push('|-------|--------|-------|-------|');

    const sorted = [
      ...cat.checks.filter(c => c.status === 'fail'),
      ...cat.checks.filter(c => c.status === 'warning'),
      ...cat.checks.filter(c => c.status === 'pass'),
    ];

    for (const check of sorted) {
      const icon = STATUS_ICON[check.status] ?? '';
      const value = (check.value ?? '').replace(/\|/g, '\\|');
      const desc = (check.description ?? '').replace(/\|/g, '\\|');
      lines.push(`| ${check.label} | ${icon} ${check.status} | ${value} | ${desc} |`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [Webbeet UX Audit](https://ux-audit.exlinelabs.co.uk) - free instant website audit across 51 checks*`);

  return lines.join('\n');
}

export function downloadMarkdown(
  url: string,
  overallScore: number,
  categories: Partial<AuditCategories>,
  scannedAt?: string,
): void {
  const md = generateMarkdown(url, overallScore, categories, scannedAt);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const href = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const hostname = (() => { try { return new URL(url).hostname; } catch { return 'audit'; } })();
  a.href = href;
  a.download = `webbeet-audit-${hostname}.md`;
  a.click();
  URL.revokeObjectURL(href);
}

// ── PDF export ────────────────────────────────────────────────────────────────

export function exportPdf(): void {
  window.print();
}
